#!/usr/bin/env node
import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";

function isLaravelRepo(root) {
  return existsSync(join(root, "artisan")) && existsSync(join(root, "composer.json"));
}

function listExisting(root, candidates) {
  return candidates.filter((p) => existsSync(join(root, p))).sort();
}

function listFiles(root, dir, predicate = () => true) {
  const base = join(root, dir);
  if (!existsSync(base)) return [];
  return readdirSync(base, { withFileTypes: true })
    .filter((entry) => entry.isFile() && predicate(entry.name))
    .map((entry) => `${dir}/${entry.name}`)
    .sort();
}

function planningRefs(root) {
  const dir = join(root, ".planning", "codebase");
  if (!existsSync(dir)) return [];
  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md"))
    .map((entry) => `.planning/codebase/${entry.name}`)
    .sort();
}

function writeArtifacts(root) {
  const arcova = join(root, ".arcova");
  mkdirSync(arcova, { recursive: true });

  const inventory = listExisting(root, ["app/Domains", "app/Core", "app/Modules"]);
  const providers = listFiles(root, "app/Providers", (name) => name.endsWith(".php"));
  const routes = listFiles(root, "routes", (name) => name.endsWith(".php"));
  const tests = listExisting(root, ["tests/Feature", "tests/Unit", "tests/Browser", "tests/Pest.php"]);
  const refs = planningRefs(root);
  const security = refs.includes(".planning/codebase/SECURITY.md")
    ? ".planning/codebase/SECURITY.md"
    : "(none found)";

  const map = [
    "# Arcova Codebase Map",
    "",
    "Generated by `scripts/arcova-map.mjs`. Keep this compact: entrypoints, not a repo dump.",
    "",
    "## Application Roots",
    ...(inventory.length ? inventory.map((p) => `- ${p}`) : ["- (no app/Domains, app/Core, or app/Modules found)"]),
    "",
    "## Routes",
    ...(routes.length ? routes.map((p) => `- ${p}`) : ["- (no route files found)"]),
    "",
    "## Providers",
    ...(providers.length ? providers.map((p) => `- ${p}`) : ["- (no provider files found)"]),
    "",
    "## Tests",
    ...(tests.length ? tests.map((p) => `- ${p}`) : ["- (no tests layout found)"]),
    "",
    "## Planning References",
    ...(refs.length ? refs.map((p) => `- ${p}`) : ["- (none found)"]),
    "",
    "## Security Source",
    `- ${security}`,
    "",
    "## Focused Verification Commands",
    "- `php artisan test tests/Feature/ExampleTest.php`",
    "- `php artisan test --filter=example`",
    "- `npm run types` when frontend types are affected",
    "- `php vendor/bin/pint --dirty` only when formatting is explicit",
    "",
  ].join("\n");

  const rules = [
    "# Arcova Rules",
    "",
    "- Work in the smallest coherent file set.",
    "- Read local docs and nearby patterns before editing.",
    "- Preserve tenant boundaries and policy checks.",
    "- Do not edit existing migrations unless explicitly instructed.",
    "- Do not touch `.env`, secrets, tokens, payment, auth, session, or tenancy code without explicit approval.",
    "- Run focused verification after edits.",
    "- Use Pint only when formatting is explicitly requested.",
    "- Hand off when tripwires block or the change exceeds the safe file limit.",
    "",
  ].join("\n");

  const guards = {
    hardBlock: [
      "**/.env",
      "**/.env.*",
      "**/*secret*",
      "**/*credential*",
      "database/migrations/*.php",
      "app/**/Auth/**",
      "app/**/Session/**",
      "app/**/Token/**",
      "app/**/Billing/**",
      "app/**/Payment/**",
      "app/**/Webhook/**",
      "app/**/Tenancy/**",
    ],
    softFileLimit: 5,
    hardFileLimit: 12,
    generated: ["resources/js/wayfinder/**", "bootstrap/ssr/**"],
  };

  const files = [
    [join(arcova, "MAP.md"), map],
    [join(arcova, "RULES.md"), rules],
    [join(arcova, "guards.json"), JSON.stringify(guards, null, 2) + "\n"],
  ];
  for (const [path, content] of files) writeFileSync(path, content);
  return files.map(([path]) => path);
}

export function buildArcovaArtifacts(repoPath) {
  const root = resolve(repoPath);
  if (!isLaravelRepo(root)) throw new Error(`${root} is not a Laravel repo (missing artisan or composer.json)`);
  return writeArtifacts(root);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const target = process.argv[2] || process.cwd();
  const generated = buildArcovaArtifacts(target);
  for (const file of generated) {
    console.log(`Generated ${relative(resolve(target), file).replaceAll("\\", "/")}`);
  }
}
